### ISSUE TITLE
Refactor project file format and Project struct

### ISSUE THREAD

**Issue by spaulg** [spaulg/solo#41]
## Description

Refactor the project file format around `x-solo` extension keys. This is to allow additional config options to be declared without having to overuse the x-* notation on every piece of config.

The format might look like:

```yaml
x-solo:
    # Solo project wide specific config

services:
    test:
        x-solo:
            # Solo service specific config
            workflow_timeout: 60
        
            workflows:
                build:
                    - name: Do something
                      command: /bin/command
                      cwd: /home/user

                pre_start:
                post_start:
```

Also refactor the Project struct to embed the Composer project type and extend the structs accordingly.
